// @file: SO-5 — golden snapshot of the surface actually shipped to a consumer: what `sync` mirrors
//   into `ai/directives/`, what `sync-skills` mirrors into `.claude/skills/`, and what `npm pack`
//   puts in the published tarball. Plus a repo-wide leak scan: none of that shipped content may
//   carry an absolute developer home-directory path (the class of leak found and fixed in this same
//   task at `ai/directives/agent-inbox/golden-chat-output.example.md:176` — a real chat example
//   that baked in the report author's own `/Users/<name>/.gennady/...` path).
// @consumers: release regression suite
// @tasks: N/A

// SO-5 (ai/drafts/research/sdd-v1-to-v2-transfer/32-TRACK-SYNC-OWNERSHIP.md §4.1, 61-TASK-BOARD.md
//   §1): none of `scanDirectives`/`scanSkills`/`npm pack` is touched here — only observed. This
//   file, like V-01/T-9 before it, is a frozen golden: the file LIST that ships is committed
//   verbatim and any drift (a file added, removed, or renamed on the shipped surface) fails the
//   test until it is deliberately regenerated by an owning task, via `UPDATE_SURFACE_GOLDEN=1`
//   (same convention as `UPDATE_VERIFY_GOLDEN=1` in `shared/sdd/__tests__/preset-node-golden.test.ts`
//   — this is the second use of the `UPDATE_*_GOLDEN=1` family, not a new one).

import { describe, it } from 'node:test';
import assert from 'node:assert/strict';
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { spawnSync } from 'node:child_process';
import { scanDirectives } from '../../../../cli/cmd/sync/sync-core.ts';
import { scanSkills } from '../../../../cli/cmd/sync-skills/sync-skills-core.ts';
import { normalize, SYNC_PATH_RULES, SYNC_SKILLS_PATH_RULES } from '../path-normalizer.ts';

const ROOT = resolve(import.meta.dirname, '../../../..');
const GOLDEN_DIR = import.meta.dirname;

function updateGolden(): boolean {
  return process.env.UPDATE_SURFACE_GOLDEN === '1';
}

/**
 * @purpose Compare a sorted, newline-joined list of relative paths against a committed golden text
 *   file, or (re)write it when `UPDATE_SURFACE_GOLDEN=1` is set.
 * @param name Golden file basename (under this directory).
 * @param actualPaths Relative paths that make up the observed surface.
 */
function assertGoldenList(name: string, actualPaths: readonly string[]): void {
  const goldenPath = resolve(GOLDEN_DIR, name);
  const actual = `${[...actualPaths].sort().join('\n')}\n`;
  if (updateGolden()) {
    writeFileSync(goldenPath, actual);
    return;
  }
  assert.ok(
    existsSync(goldenPath),
    `missing ${name} — regenerate with UPDATE_SURFACE_GOLDEN=1 npm test`
  );
  const expected = readFileSync(goldenPath, 'utf-8');
  assert.strictEqual(
    actual,
    expected,
    `${name} drifted from the frozen deployed-surface snapshot (a file was added, removed, or ` +
      'renamed on a surface that ships to consumers via sync/sync-skills/npm). If the change is ' +
      'deliberate, regenerate with: UPDATE_SURFACE_GOLDEN=1 npm test'
  );
}

// Absolute-home-directory leak: `/Users/<real-name>/...` or `/home/<real-name>/...`. A templated
// placeholder segment (`<user>`, as used in ai/skills/workspace-permission-setup/SKILL.md) is not a
// leak — the negative lookahead excludes it.
const DEV_HOME_LEAK = /\/(?:Users|home)\/(?!<)[\w.-]+\//;

function findLeaks(files: ReadonlyMap<string, string>): string[] {
  const offenders: string[] = [];
  for (const [relPath, content] of files) {
    if (DEV_HOME_LEAK.test(content)) offenders.push(relPath);
  }
  return offenders;
}

// `npm pack` reads and hashes the whole would-be tarball — real subprocess cost, unlike the two
// pure in-process `scan*` calls above. Both its below need its file list; spawning it once and
// sharing the result (rather than once per `it`) keeps this file's contribution to the outer
// test-topology run's real wall-clock/CPU budget to a single subprocess instead of two.
let packFilesCache: string[] | undefined;
function packFiles(): string[] {
  if (packFilesCache) return packFilesCache;
  const result = spawnSync('npm', ['pack', '--dry-run', '--json'], {
    cwd: ROOT,
    encoding: 'utf-8',
  });
  assert.equal(result.status, 0, result.stderr);
  const [{ files }] = JSON.parse(result.stdout) as [{ files: Array<{ path: string }> }];
  packFilesCache = files.map((f) => f.path);
  return packFilesCache;
}

describe('deployed surface (SO-5)', () => {
  it('sync ships exactly the frozen ai/directives/** file list', () => {
    const files = scanDirectives(resolve(ROOT, 'ai/directives'));
    assertGoldenList('deployed-surface.directives.golden.txt', files);
  });

  it('sync-skills ships exactly the frozen ai/skills/** file list', () => {
    const bySkill = scanSkills(resolve(ROOT, 'ai/skills'));
    const files: string[] = [];
    for (const [skillName, contents] of bySkill) {
      for (const relPath of contents.keys()) files.push(`${skillName}/${relPath}`);
    }
    assertGoldenList('deployed-surface.skills.golden.txt', files);
  });

  it('npm pack --dry-run ships exactly the frozen tarball file list', () => {
    // `dist/**` is excluded from the frozen list: it is Vite's build OUTPUT, not a checked-in
    // repository source. `dist/chunks/*` filenames carry a content hash chosen by Vite's internal
    // chunk splitting (`dist/chunks/foo-<hash>.js`) — that hash, and even the chunk COUNT, can
    // change between two builds of the identical source (a fresh `npm run build` regenerates them,
    // and nothing in this repo pins either). Freezing those paths made this `it` fail
    // deterministically after any build, on this tree and on any fresh clone that never built at
    // all (`dist/` is gitignored — see `.gitignore:11` — so `npm pack --dry-run` on a fresh clone
    // omits `dist/**` entirely, since `package.json`'s `files: ["dist/**/*", ...]` glob matches
    // nothing). The stable, checked-in package surface is what this golden freezes; whether `dist/`
    // exists, and what its build produced this run, is orthogonal to it.
    const files = packFiles().filter((path) => path !== 'dist' && !path.startsWith('dist/'));
    assertGoldenList('deployed-surface.tarball.golden.txt', files);
  });

  it('ships no file (directives ∪ skills ∪ tarball) with a developer home-directory path leak', () => {
    const contentByRelPath = new Map<string, string>();

    // `sync` normalizes every file's content with SYNC_PATH_RULES before writing it into a
    // consumer project — that normalized content, not the raw source bytes, is what a consumer
    // actually receives.
    for (const relPath of scanDirectives(resolve(ROOT, 'ai/directives'))) {
      const raw = readFileSync(resolve(ROOT, 'ai/directives', relPath), 'utf-8');
      contentByRelPath.set(`sync:ai/directives/${relPath}`, normalize(raw, SYNC_PATH_RULES));
    }

    // `sync-skills` normalizes with SYNC_SKILLS_PATH_RULES (superset: also rewrites the skills
    // tilde rule).
    const bySkill = scanSkills(resolve(ROOT, 'ai/skills'));
    for (const [skillName, contents] of bySkill) {
      for (const [relPath, buf] of contents) {
        contentByRelPath.set(
          `sync-skills:${skillName}/${relPath}`,
          normalize(buf.toString('utf-8'), SYNC_SKILLS_PATH_RULES)
        );
      }
    }

    // The npm tarball ships raw repository bytes — no path-normalizer pass runs over it.
    for (const path of packFiles()) {
      const abs = resolve(ROOT, path);
      let content: string;
      try {
        content = readFileSync(abs, 'utf-8');
      } catch {
        continue; // binary or unreadable as utf-8 — not a text leak surface
      }
      contentByRelPath.set(`tarball:${path}`, content);
    }

    assert.deepEqual(findLeaks(contentByRelPath), []);
  });
});
